### ISSUE TITLE
mocha integration

### ISSUE THREAD

**Issue by boneskull** [bahmutov/snap-shot-it#468]
I'm thinking about pulling this module (or some portion thereof) into Mocha (`snap-shot-compare` and `snap-shot-core` will absolutely be useful, regardless of how it's implemented).  A lot of people would love this feature--Mocha itself would use it!  @bahmutov seemed open to the idea.

So... what would this look like?  If `snap-shot-it` was implemented in Mocha core, what would be done differently?

Here are some notes

## Mocha is Unopinionated

For better or worse, Mocha doesn't ship with an assertion library.  Yet `snap-shot-it` _does_ make assertions (in that it throws exceptions).  To that end, maybe it'd be better for a hypothetical Mocha-provided snapshot function to--instead of throw if it fails to match--return an _object of a specific shape_ which assertion libraries (or plugins) could then interpret.  For example,

```js
// e.g. with chai

const chai = require('chai');
const chaiSnapShot = require('chai-snap-shot');  // hypothetical plugin
const expect = chai.use(chapSnapShot);

// without plugin
it('should be 42', () => {
  expect(snapshot(41)).to.deep.equal({
    matched: false, // true if matched
    diff: (/* insert diff here */), // undefined if matched
    file: (/* snapshot file */),
    otherInfo: (/* whatever */)
  });
});

// with plugin
it('should be 42', () => {
  expect(snapshot(41)).to.equal.snapshot();
});

```

Is there a commonly-used "schema" we could use out there already?

##  No More Globals

Mocha stuffs things in `global`. I don't really want to stuff _more_ things there.  So, what do we have to work with?

1. Export snapshot from the main module, e.g. `const {snapshot} = require('mocha')`.  This is maybe not as straightforward to implement as you'd hope
2. Attach it to the global "test" function, e.g., `it.snapshot()`
3. Attach it to the test context, e.g., `this.snapshot()` 😒 

## Backwards compat

I don't want to break _current_ users of `snap-shot-it`.  What do we need to be aware of?  I think avoiding use of the same env var names, at minimum.  What about snapshot filepaths and filenames?

**Comment by bajtos** [comment]
I would love to have snapshot-based assertions built into Mocha :+1:

My thoughts on the questions posted above:

> For better or worse, Mocha doesn't ship with an assertion library. Yet snap-shot-it does make assertions (in that it throws exceptions). To that end, maybe it'd be better for a hypothetical Mocha-provided snapshot function to--instead of throw if it fails to match--return an object of a specific shape which assertion libraries (or plugins) could then interpret.

If we want to pretend that snapshots are provided by the assertion library like chai, then ideally our test code should not need to access anything from `mocha`, it should use the assertion API.

```js
const chai = require('chai');
const chaiSnapShot = require('chai-snap-shot');  // hypothetical plugin
const expect = chai.use(chapSnapShot);

// with plugin
it('should be 42', () => {
  expect(41).to.matchSnapshot();
});
```

I am a bit concerned about the friction the setup process adds. If I have to use a 3rd-party plugin for my assertion library, then perhaps I can directly use `snap-shot-it` and don't need any changes in Mocha?

> Mocha stuffs things in global. I don't really want to stuff more things there. So, what do we have to work with?

+1 to avoid another `global` thing.

> Export snapshot from the main module, e.g. `const {snapshot} = require('mocha')`. This is maybe not as straightforward to implement as you'd hope.

Personally, I like this approach best. 

Going one step further, it would be great if I could load test interface methods this way too, e.g.

```js
const {describe, it, snapshot} = require('mocha');
```

> Attach it to the global "test" function, e.g., `it.snapshot()`

This looks weird to me. Just consider the test code:

```js
it('should be 42', () => {
  it.snapshot(41);
});
```

So far, the test code written using Mocha+Chai or Mocha+Should reads like an English text. "it snapshot" does not make sense to me.

> Attach it to the test context, e.g., `this.snapshot()`

This makes more sense than `it.snapshot()` to me, although it still does not read like English. However, `this` methods are not very ergonomic because if we want to use them, then we have to write tests usin full `function` syntax and cannot use `=>` shorthand.

**Comment by boneskull** [comment]
I think, perhaps, native snapshots aren't the best thing for Mocha; after much consideration, I think they are out-of-scope; they fall within the purview of assertion libraries.  That said, I think there are ways for Mocha to better support "plugins" such as this one.
